# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Service CI

on:
  workflow_call:
    inputs:
      APP_VERSION_INCREMENT_TYPE:
        type: string
        required: true
      APP_VERSION_VISIBILITY:
        type: string
        required: true
      WORK_DIR:
        type: string
        required: true

jobs:
  test:
    name: lint and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Get app metadata
        id: app-metadata
        uses: vtex/app-metadata-action@main
        with:
          version-visibility: ${{ inputs.APP_VERSION_VISIBILITY }}
          version-increment-type: ${{ inputs.APP_VERSION_INCREMENT_TYPE }}

      - name: Bump version before building
        run: yarn version --new-version ${{steps.app-metadata.outputs.next-app-version}} --no-git-tag-version
        working-directory: ${{ inputs.WORK_DIR }}

      - run: yarn
        working-directory: ${{ inputs.WORK_DIR }}
      - run: yarn run lint
        working-directory: ${{ inputs.WORK_DIR }}
      - run: yarn run test
        working-directory: ${{ inputs.WORK_DIR }}
