# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend Service CI

on:
  workflow_call:

jobs:
  test:
    name: lint and test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: set-version-visibility-to-unpublished
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: echo "APP_VERSION_VISIBILITY=unpublished" >> $GITHUB_ENV

      - name: set-version-visibility-to-development
        if: ${{ !(github.event_name == 'push' && github.ref_name == 'main') }}
        run: echo "APP_VERSION_VISIBILITY=development" >> $GITHUB_ENV

      - name: Get app metadata
        id: app-metadata
        uses: vtex/app-metadata-action@main
        with:
          version-visibility: ${{ env.APP_VERSION_VISIBILITY }}
          version-increment-type: 'patch'

      - name: Export env.WORK_DIR as the package path
        run: echo "WORK_DIR=${{ steps.app-metadata.outputs.frontend-folder }}" >> $GITHUB_ENV

      - name: Bump version before building
        run: yarn version --new-version ${{steps.app-metadata.outputs.next-app-version}} --no-git-tag-version
        working-directory: ${{ env.WORK_DIR }}

      - run: yarn
        working-directory: ${{ env.WORK_DIR }}
      - run: yarn run lint
        working-directory: ${{ env.WORK_DIR }}
      - run: yarn run test
        working-directory: ${{ env.WORK_DIR }}
